[2016-03-06 22:38:30 +0100] [5245] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:38:30 +0100] [5245] [INFO] Listening at: http://192.168.3.13:8000 (5245)
[2016-03-06 22:38:30 +0100] [5245] [INFO] Using worker: sync
[2016-03-06 22:38:30 +0100] [5249] [INFO] Booting worker with pid: 5249
[2016-03-06 22:38:30 +0100] [5250] [INFO] Booting worker with pid: 5250
[2016-03-06 22:40:00 +0100] [5294] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:40:01 +0100] [5294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:01 +0100] [5294] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:02 +0100] [5294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:02 +0100] [5294] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:03 +0100] [5294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:03 +0100] [5294] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:04 +0100] [5294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:04 +0100] [5294] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:05 +0100] [5294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:05 +0100] [5294] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:06 +0100] [5294] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:40:13 +0100] [5318] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:40:13 +0100] [5318] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:13 +0100] [5318] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:14 +0100] [5318] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:14 +0100] [5318] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:15 +0100] [5318] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:15 +0100] [5318] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:16 +0100] [5318] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:16 +0100] [5318] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:17 +0100] [5318] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:17 +0100] [5318] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:18 +0100] [5318] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:40:25 +0100] [5344] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:40:25 +0100] [5344] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:25 +0100] [5344] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:26 +0100] [5344] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:26 +0100] [5344] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:27 +0100] [5344] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:27 +0100] [5344] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:28 +0100] [5344] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:28 +0100] [5344] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:29 +0100] [5344] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:29 +0100] [5344] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:30 +0100] [5344] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:40:37 +0100] [5360] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:40:37 +0100] [5360] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:37 +0100] [5360] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:38 +0100] [5360] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:38 +0100] [5360] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:39 +0100] [5360] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:39 +0100] [5360] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:40 +0100] [5360] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:40 +0100] [5360] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:41 +0100] [5360] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:41 +0100] [5360] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:42 +0100] [5360] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:40:49 +0100] [5372] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:40:49 +0100] [5372] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:49 +0100] [5372] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:50 +0100] [5372] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:50 +0100] [5372] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:51 +0100] [5372] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:51 +0100] [5372] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:52 +0100] [5372] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:52 +0100] [5372] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:53 +0100] [5372] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:40:53 +0100] [5372] [ERROR] Retrying in 1 second.
[2016-03-06 22:40:54 +0100] [5372] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:41:01 +0100] [5384] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:41:01 +0100] [5384] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:01 +0100] [5384] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:02 +0100] [5384] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:02 +0100] [5384] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:03 +0100] [5384] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:03 +0100] [5384] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:04 +0100] [5384] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:04 +0100] [5384] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:05 +0100] [5384] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:05 +0100] [5384] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:06 +0100] [5384] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:41:12 +0100] [5395] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:41:12 +0100] [5395] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:12 +0100] [5395] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:13 +0100] [5395] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:13 +0100] [5395] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:14 +0100] [5395] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:14 +0100] [5395] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:15 +0100] [5395] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:15 +0100] [5395] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:16 +0100] [5395] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:16 +0100] [5395] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:17 +0100] [5395] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:41:24 +0100] [5404] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:41:24 +0100] [5404] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:24 +0100] [5404] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:25 +0100] [5404] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:25 +0100] [5404] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:26 +0100] [5404] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:26 +0100] [5404] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:27 +0100] [5404] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:27 +0100] [5404] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:28 +0100] [5404] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:28 +0100] [5404] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:29 +0100] [5404] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:41:35 +0100] [5416] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:41:36 +0100] [5416] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:36 +0100] [5416] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:37 +0100] [5416] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:37 +0100] [5416] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:38 +0100] [5416] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:38 +0100] [5416] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:39 +0100] [5416] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:39 +0100] [5416] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:40 +0100] [5416] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:40 +0100] [5416] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:41 +0100] [5416] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:41:47 +0100] [5426] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:41:47 +0100] [5426] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:47 +0100] [5426] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:48 +0100] [5426] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:48 +0100] [5426] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:49 +0100] [5426] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:49 +0100] [5426] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:50 +0100] [5426] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:50 +0100] [5426] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:51 +0100] [5426] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:51 +0100] [5426] [ERROR] Retrying in 1 second.
[2016-03-06 22:41:52 +0100] [5426] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:41:59 +0100] [5437] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:41:59 +0100] [5437] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:41:59 +0100] [5437] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:00 +0100] [5437] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:00 +0100] [5437] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:01 +0100] [5437] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:01 +0100] [5437] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:02 +0100] [5437] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:02 +0100] [5437] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:03 +0100] [5437] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:03 +0100] [5437] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:04 +0100] [5437] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:42:10 +0100] [5448] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:42:10 +0100] [5448] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:10 +0100] [5448] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:11 +0100] [5448] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:11 +0100] [5448] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:12 +0100] [5448] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:12 +0100] [5448] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:14 +0100] [5448] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:14 +0100] [5448] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:15 +0100] [5448] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:15 +0100] [5448] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:16 +0100] [5448] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:42:22 +0100] [5458] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:42:22 +0100] [5458] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:22 +0100] [5458] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:23 +0100] [5458] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:23 +0100] [5458] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:24 +0100] [5458] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:24 +0100] [5458] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:25 +0100] [5458] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:25 +0100] [5458] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:26 +0100] [5458] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:26 +0100] [5458] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:27 +0100] [5458] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:42:34 +0100] [5469] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:42:34 +0100] [5469] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:34 +0100] [5469] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:35 +0100] [5469] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:35 +0100] [5469] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:36 +0100] [5469] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:36 +0100] [5469] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:37 +0100] [5469] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:37 +0100] [5469] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:38 +0100] [5469] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:38 +0100] [5469] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:39 +0100] [5469] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:42:45 +0100] [5481] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:42:46 +0100] [5481] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:46 +0100] [5481] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:47 +0100] [5481] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:47 +0100] [5481] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:48 +0100] [5481] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:48 +0100] [5481] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:49 +0100] [5481] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:49 +0100] [5481] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:50 +0100] [5481] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:50 +0100] [5481] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:51 +0100] [5481] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:42:57 +0100] [5491] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:42:57 +0100] [5491] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:57 +0100] [5491] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:58 +0100] [5491] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:58 +0100] [5491] [ERROR] Retrying in 1 second.
[2016-03-06 22:42:59 +0100] [5491] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:42:59 +0100] [5491] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:00 +0100] [5491] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:00 +0100] [5491] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:01 +0100] [5491] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:01 +0100] [5491] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:02 +0100] [5491] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:43:09 +0100] [5502] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:43:09 +0100] [5502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:09 +0100] [5502] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:10 +0100] [5502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:10 +0100] [5502] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:11 +0100] [5502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:11 +0100] [5502] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:12 +0100] [5502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:12 +0100] [5502] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:13 +0100] [5502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:13 +0100] [5502] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:14 +0100] [5502] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:43:20 +0100] [5513] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:43:21 +0100] [5513] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:21 +0100] [5513] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:22 +0100] [5513] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:22 +0100] [5513] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:23 +0100] [5513] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:23 +0100] [5513] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:24 +0100] [5513] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:24 +0100] [5513] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:25 +0100] [5513] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:25 +0100] [5513] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:26 +0100] [5513] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:43:32 +0100] [5524] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:43:32 +0100] [5524] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:32 +0100] [5524] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:33 +0100] [5524] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:33 +0100] [5524] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:34 +0100] [5524] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:34 +0100] [5524] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:35 +0100] [5524] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:35 +0100] [5524] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:36 +0100] [5524] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:37 +0100] [5524] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:38 +0100] [5524] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:43:44 +0100] [5536] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:43:44 +0100] [5536] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:44 +0100] [5536] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:45 +0100] [5536] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:45 +0100] [5536] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:46 +0100] [5536] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:46 +0100] [5536] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:47 +0100] [5536] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:47 +0100] [5536] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:48 +0100] [5536] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:48 +0100] [5536] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:49 +0100] [5536] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:43:56 +0100] [5546] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:43:56 +0100] [5546] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:56 +0100] [5546] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:57 +0100] [5546] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:57 +0100] [5546] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:58 +0100] [5546] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:58 +0100] [5546] [ERROR] Retrying in 1 second.
[2016-03-06 22:43:59 +0100] [5546] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:43:59 +0100] [5546] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:00 +0100] [5546] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:00 +0100] [5546] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:01 +0100] [5546] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:44:08 +0100] [5556] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:44:08 +0100] [5556] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:08 +0100] [5556] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:09 +0100] [5556] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:09 +0100] [5556] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:10 +0100] [5556] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:10 +0100] [5556] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:11 +0100] [5556] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:11 +0100] [5556] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:12 +0100] [5556] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:12 +0100] [5556] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:13 +0100] [5556] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:44:19 +0100] [5572] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:44:19 +0100] [5572] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:19 +0100] [5572] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:20 +0100] [5572] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:20 +0100] [5572] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:21 +0100] [5572] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:21 +0100] [5572] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:22 +0100] [5572] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:22 +0100] [5572] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:23 +0100] [5572] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:23 +0100] [5572] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:24 +0100] [5572] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:44:31 +0100] [5582] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:44:31 +0100] [5582] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:31 +0100] [5582] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:32 +0100] [5582] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:32 +0100] [5582] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:33 +0100] [5582] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:33 +0100] [5582] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:34 +0100] [5582] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:34 +0100] [5582] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:35 +0100] [5582] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:35 +0100] [5582] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:36 +0100] [5582] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:44:42 +0100] [5594] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:44:43 +0100] [5594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:43 +0100] [5594] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:44 +0100] [5594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:44 +0100] [5594] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:45 +0100] [5594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:45 +0100] [5594] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:46 +0100] [5594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:46 +0100] [5594] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:47 +0100] [5594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:47 +0100] [5594] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:48 +0100] [5594] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:44:54 +0100] [5604] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:44:54 +0100] [5604] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:54 +0100] [5604] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:55 +0100] [5604] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:55 +0100] [5604] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:56 +0100] [5604] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:56 +0100] [5604] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:57 +0100] [5604] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:57 +0100] [5604] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:58 +0100] [5604] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:44:58 +0100] [5604] [ERROR] Retrying in 1 second.
[2016-03-06 22:44:59 +0100] [5604] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:45:06 +0100] [5615] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:45:06 +0100] [5615] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:06 +0100] [5615] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:07 +0100] [5615] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:07 +0100] [5615] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:08 +0100] [5615] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:08 +0100] [5615] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:09 +0100] [5615] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:09 +0100] [5615] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:10 +0100] [5615] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:10 +0100] [5615] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:11 +0100] [5615] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:45:18 +0100] [5625] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:45:18 +0100] [5625] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:18 +0100] [5625] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:19 +0100] [5625] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:19 +0100] [5625] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:20 +0100] [5625] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:20 +0100] [5625] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:21 +0100] [5625] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:21 +0100] [5625] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:22 +0100] [5625] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:22 +0100] [5625] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:23 +0100] [5625] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:45:29 +0100] [5642] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:45:29 +0100] [5642] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:29 +0100] [5642] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:30 +0100] [5642] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:30 +0100] [5642] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:31 +0100] [5642] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:31 +0100] [5642] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:32 +0100] [5642] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:32 +0100] [5642] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:33 +0100] [5642] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:33 +0100] [5642] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:34 +0100] [5642] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:45:41 +0100] [5652] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:45:41 +0100] [5652] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:41 +0100] [5652] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:42 +0100] [5652] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:42 +0100] [5652] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:43 +0100] [5652] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:43 +0100] [5652] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:44 +0100] [5652] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:44 +0100] [5652] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:45 +0100] [5652] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:45 +0100] [5652] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:46 +0100] [5652] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:45:52 +0100] [5663] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:45:53 +0100] [5663] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:53 +0100] [5663] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:54 +0100] [5663] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:54 +0100] [5663] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:55 +0100] [5663] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:55 +0100] [5663] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:56 +0100] [5663] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:56 +0100] [5663] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:57 +0100] [5663] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:45:57 +0100] [5663] [ERROR] Retrying in 1 second.
[2016-03-06 22:45:58 +0100] [5663] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:46:04 +0100] [5673] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:46:04 +0100] [5673] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:04 +0100] [5673] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:05 +0100] [5673] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:05 +0100] [5673] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:06 +0100] [5673] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:06 +0100] [5673] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:07 +0100] [5673] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:07 +0100] [5673] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:08 +0100] [5673] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:08 +0100] [5673] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:09 +0100] [5673] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:46:16 +0100] [5683] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:46:16 +0100] [5683] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:16 +0100] [5683] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:17 +0100] [5683] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:17 +0100] [5683] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:18 +0100] [5683] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:18 +0100] [5683] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:19 +0100] [5683] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:19 +0100] [5683] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:20 +0100] [5683] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:20 +0100] [5683] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:21 +0100] [5683] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:46:28 +0100] [5694] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:46:28 +0100] [5694] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:28 +0100] [5694] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:29 +0100] [5694] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:29 +0100] [5694] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:30 +0100] [5694] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:30 +0100] [5694] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:31 +0100] [5694] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:31 +0100] [5694] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:32 +0100] [5694] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:32 +0100] [5694] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:33 +0100] [5694] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:46:40 +0100] [5707] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:46:40 +0100] [5707] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:40 +0100] [5707] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:41 +0100] [5707] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:41 +0100] [5707] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:42 +0100] [5707] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:42 +0100] [5707] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:43 +0100] [5707] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:43 +0100] [5707] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:44 +0100] [5707] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:44 +0100] [5707] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:45 +0100] [5707] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:46:51 +0100] [5716] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:46:51 +0100] [5716] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:51 +0100] [5716] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:52 +0100] [5716] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:52 +0100] [5716] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:53 +0100] [5716] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:53 +0100] [5716] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:54 +0100] [5716] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:54 +0100] [5716] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:55 +0100] [5716] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:46:55 +0100] [5716] [ERROR] Retrying in 1 second.
[2016-03-06 22:46:56 +0100] [5716] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:47:03 +0100] [5727] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:47:03 +0100] [5727] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:03 +0100] [5727] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:04 +0100] [5727] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:04 +0100] [5727] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:05 +0100] [5727] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:05 +0100] [5727] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:06 +0100] [5727] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:06 +0100] [5727] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:07 +0100] [5727] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:07 +0100] [5727] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:08 +0100] [5727] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:47:14 +0100] [5738] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:47:15 +0100] [5738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:15 +0100] [5738] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:16 +0100] [5738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:16 +0100] [5738] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:17 +0100] [5738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:17 +0100] [5738] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:18 +0100] [5738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:18 +0100] [5738] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:19 +0100] [5738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:19 +0100] [5738] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:20 +0100] [5738] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:47:29 +0100] [5750] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:47:29 +0100] [5750] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:29 +0100] [5750] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:30 +0100] [5750] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:30 +0100] [5750] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:31 +0100] [5750] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:31 +0100] [5750] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:32 +0100] [5750] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:32 +0100] [5750] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:33 +0100] [5750] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:33 +0100] [5750] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:34 +0100] [5750] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:47:41 +0100] [5773] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:47:41 +0100] [5773] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:41 +0100] [5773] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:42 +0100] [5773] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:42 +0100] [5773] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:43 +0100] [5773] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:43 +0100] [5773] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:44 +0100] [5773] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:44 +0100] [5773] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:46 +0100] [5773] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:46 +0100] [5773] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:47 +0100] [5773] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:47:53 +0100] [5786] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:47:54 +0100] [5786] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:54 +0100] [5786] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:55 +0100] [5786] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:55 +0100] [5786] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:56 +0100] [5786] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:56 +0100] [5786] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:57 +0100] [5786] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:57 +0100] [5786] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:58 +0100] [5786] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:47:58 +0100] [5786] [ERROR] Retrying in 1 second.
[2016-03-06 22:47:59 +0100] [5786] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:48:05 +0100] [5798] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:48:05 +0100] [5798] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:05 +0100] [5798] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:06 +0100] [5798] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:06 +0100] [5798] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:07 +0100] [5798] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:07 +0100] [5798] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:08 +0100] [5798] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:08 +0100] [5798] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:09 +0100] [5798] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:09 +0100] [5798] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:10 +0100] [5798] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:48:17 +0100] [5808] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:48:17 +0100] [5808] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:17 +0100] [5808] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:18 +0100] [5808] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:18 +0100] [5808] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:19 +0100] [5808] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:19 +0100] [5808] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:20 +0100] [5808] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:20 +0100] [5808] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:21 +0100] [5808] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:21 +0100] [5808] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:22 +0100] [5808] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:48:29 +0100] [5820] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:48:29 +0100] [5820] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:29 +0100] [5820] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:30 +0100] [5820] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:30 +0100] [5820] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:31 +0100] [5820] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:31 +0100] [5820] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:32 +0100] [5820] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:32 +0100] [5820] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:33 +0100] [5820] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:33 +0100] [5820] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:34 +0100] [5820] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:48:40 +0100] [5831] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:48:41 +0100] [5831] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:41 +0100] [5831] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:42 +0100] [5831] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:42 +0100] [5831] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:43 +0100] [5831] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:43 +0100] [5831] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:44 +0100] [5831] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:44 +0100] [5831] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:45 +0100] [5831] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:45 +0100] [5831] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:46 +0100] [5831] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:48:53 +0100] [5841] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:48:53 +0100] [5841] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:53 +0100] [5841] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:54 +0100] [5841] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:54 +0100] [5841] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:55 +0100] [5841] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:55 +0100] [5841] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:56 +0100] [5841] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:56 +0100] [5841] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:57 +0100] [5841] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:48:57 +0100] [5841] [ERROR] Retrying in 1 second.
[2016-03-06 22:48:58 +0100] [5841] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:49:05 +0100] [5854] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:49:05 +0100] [5854] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:05 +0100] [5854] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:06 +0100] [5854] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:06 +0100] [5854] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:07 +0100] [5854] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:07 +0100] [5854] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:08 +0100] [5854] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:08 +0100] [5854] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:09 +0100] [5854] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:09 +0100] [5854] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:10 +0100] [5854] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:49:16 +0100] [5864] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:49:16 +0100] [5864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:16 +0100] [5864] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:17 +0100] [5864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:17 +0100] [5864] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:18 +0100] [5864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:18 +0100] [5864] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:19 +0100] [5864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:19 +0100] [5864] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:20 +0100] [5864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:20 +0100] [5864] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:21 +0100] [5864] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:49:28 +0100] [5873] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:49:29 +0100] [5873] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:29 +0100] [5873] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:30 +0100] [5873] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:30 +0100] [5873] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:31 +0100] [5873] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:31 +0100] [5873] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:32 +0100] [5873] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:32 +0100] [5873] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:33 +0100] [5873] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:33 +0100] [5873] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:34 +0100] [5873] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:49:40 +0100] [5886] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:49:40 +0100] [5886] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:40 +0100] [5886] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:41 +0100] [5886] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:41 +0100] [5886] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:42 +0100] [5886] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:42 +0100] [5886] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:43 +0100] [5886] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:43 +0100] [5886] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:44 +0100] [5886] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:44 +0100] [5886] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:45 +0100] [5886] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:49:52 +0100] [5895] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:49:52 +0100] [5895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:52 +0100] [5895] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:53 +0100] [5895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:53 +0100] [5895] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:54 +0100] [5895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:54 +0100] [5895] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:55 +0100] [5895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:55 +0100] [5895] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:56 +0100] [5895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:49:56 +0100] [5895] [ERROR] Retrying in 1 second.
[2016-03-06 22:49:57 +0100] [5895] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:50:04 +0100] [5907] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:50:04 +0100] [5907] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:04 +0100] [5907] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:05 +0100] [5907] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:05 +0100] [5907] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:06 +0100] [5907] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:06 +0100] [5907] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:07 +0100] [5907] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:07 +0100] [5907] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:08 +0100] [5907] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:08 +0100] [5907] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:09 +0100] [5907] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:50:16 +0100] [5918] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:50:16 +0100] [5918] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:16 +0100] [5918] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:17 +0100] [5918] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:17 +0100] [5918] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:18 +0100] [5918] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:18 +0100] [5918] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:19 +0100] [5918] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:19 +0100] [5918] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:20 +0100] [5918] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:20 +0100] [5918] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:21 +0100] [5918] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:50:29 +0100] [5930] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:50:29 +0100] [5930] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:29 +0100] [5930] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:30 +0100] [5930] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:30 +0100] [5930] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:31 +0100] [5930] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:31 +0100] [5930] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:32 +0100] [5930] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:32 +0100] [5930] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:33 +0100] [5930] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:33 +0100] [5930] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:34 +0100] [5930] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:50:41 +0100] [5944] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:50:41 +0100] [5944] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:41 +0100] [5944] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:42 +0100] [5944] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:42 +0100] [5944] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:43 +0100] [5944] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:43 +0100] [5944] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:44 +0100] [5944] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:44 +0100] [5944] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:45 +0100] [5944] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:45 +0100] [5944] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:46 +0100] [5944] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:50:53 +0100] [5957] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:50:53 +0100] [5957] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:53 +0100] [5957] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:54 +0100] [5957] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:54 +0100] [5957] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:55 +0100] [5957] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:55 +0100] [5957] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:56 +0100] [5957] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:56 +0100] [5957] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:57 +0100] [5957] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:50:57 +0100] [5957] [ERROR] Retrying in 1 second.
[2016-03-06 22:50:58 +0100] [5957] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:51:04 +0100] [5969] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:51:04 +0100] [5969] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:04 +0100] [5969] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:05 +0100] [5969] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:05 +0100] [5969] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:06 +0100] [5969] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:06 +0100] [5969] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:07 +0100] [5969] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:07 +0100] [5969] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:08 +0100] [5969] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:08 +0100] [5969] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:09 +0100] [5969] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:51:17 +0100] [5978] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:51:17 +0100] [5978] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:17 +0100] [5978] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:18 +0100] [5978] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:18 +0100] [5978] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:19 +0100] [5978] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:19 +0100] [5978] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:20 +0100] [5978] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:20 +0100] [5978] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:21 +0100] [5978] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:21 +0100] [5978] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:22 +0100] [5978] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:51:28 +0100] [5994] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:51:29 +0100] [5994] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:29 +0100] [5994] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:30 +0100] [5994] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:30 +0100] [5994] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:31 +0100] [5994] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:31 +0100] [5994] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:32 +0100] [5994] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:32 +0100] [5994] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:33 +0100] [5994] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:33 +0100] [5994] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:34 +0100] [5994] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:51:40 +0100] [6005] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:51:40 +0100] [6005] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:40 +0100] [6005] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:41 +0100] [6005] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:41 +0100] [6005] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:42 +0100] [6005] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:42 +0100] [6005] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:43 +0100] [6005] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:43 +0100] [6005] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:44 +0100] [6005] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:44 +0100] [6005] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:45 +0100] [6005] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:51:52 +0100] [6026] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:51:52 +0100] [6026] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:52 +0100] [6026] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:53 +0100] [6026] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:53 +0100] [6026] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:54 +0100] [6026] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:54 +0100] [6026] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:55 +0100] [6026] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:55 +0100] [6026] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:56 +0100] [6026] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:51:56 +0100] [6026] [ERROR] Retrying in 1 second.
[2016-03-06 22:51:57 +0100] [6026] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:52:04 +0100] [6038] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:52:04 +0100] [6038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:04 +0100] [6038] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:05 +0100] [6038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:05 +0100] [6038] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:06 +0100] [6038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:06 +0100] [6038] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:07 +0100] [6038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:07 +0100] [6038] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:08 +0100] [6038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:08 +0100] [6038] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:09 +0100] [6038] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:52:15 +0100] [6051] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:52:16 +0100] [6051] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:16 +0100] [6051] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:17 +0100] [6051] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:17 +0100] [6051] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:18 +0100] [6051] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:18 +0100] [6051] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:19 +0100] [6051] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:19 +0100] [6051] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:20 +0100] [6051] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:20 +0100] [6051] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:21 +0100] [6051] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:52:28 +0100] [6065] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:52:28 +0100] [6065] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:28 +0100] [6065] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:29 +0100] [6065] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:29 +0100] [6065] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:30 +0100] [6065] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:30 +0100] [6065] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:31 +0100] [6065] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:31 +0100] [6065] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:32 +0100] [6065] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:32 +0100] [6065] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:33 +0100] [6065] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:52:40 +0100] [6079] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:52:40 +0100] [6079] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:40 +0100] [6079] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:41 +0100] [6079] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:41 +0100] [6079] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:42 +0100] [6079] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:42 +0100] [6079] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:43 +0100] [6079] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:43 +0100] [6079] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:44 +0100] [6079] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:44 +0100] [6079] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:45 +0100] [6079] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:52:51 +0100] [6093] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:52:52 +0100] [6093] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:52 +0100] [6093] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:53 +0100] [6093] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:53 +0100] [6093] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:54 +0100] [6093] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:54 +0100] [6093] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:55 +0100] [6093] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:55 +0100] [6093] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:56 +0100] [6093] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:52:56 +0100] [6093] [ERROR] Retrying in 1 second.
[2016-03-06 22:52:57 +0100] [6093] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:53:04 +0100] [6103] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:53:04 +0100] [6103] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:04 +0100] [6103] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:05 +0100] [6103] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:05 +0100] [6103] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:06 +0100] [6103] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:06 +0100] [6103] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:07 +0100] [6103] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:07 +0100] [6103] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:08 +0100] [6103] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:08 +0100] [6103] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:09 +0100] [6103] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:53:15 +0100] [6114] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:53:15 +0100] [6114] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:15 +0100] [6114] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:16 +0100] [6114] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:16 +0100] [6114] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:17 +0100] [6114] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:17 +0100] [6114] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:18 +0100] [6114] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:18 +0100] [6114] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:19 +0100] [6114] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:19 +0100] [6114] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:20 +0100] [6114] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:53:28 +0100] [6124] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:53:28 +0100] [6124] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:28 +0100] [6124] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:29 +0100] [6124] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:29 +0100] [6124] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:30 +0100] [6124] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:30 +0100] [6124] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:31 +0100] [6124] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:31 +0100] [6124] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:32 +0100] [6124] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:32 +0100] [6124] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:33 +0100] [6124] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:53:40 +0100] [6136] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:53:40 +0100] [6136] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:40 +0100] [6136] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:41 +0100] [6136] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:41 +0100] [6136] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:42 +0100] [6136] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:42 +0100] [6136] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:43 +0100] [6136] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:43 +0100] [6136] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:44 +0100] [6136] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:44 +0100] [6136] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:45 +0100] [6136] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:53:51 +0100] [6150] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:53:51 +0100] [6150] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:51 +0100] [6150] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:52 +0100] [6150] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:53 +0100] [6150] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:54 +0100] [6150] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:54 +0100] [6150] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:55 +0100] [6150] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:55 +0100] [6150] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:56 +0100] [6150] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:53:56 +0100] [6150] [ERROR] Retrying in 1 second.
[2016-03-06 22:53:57 +0100] [6150] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:54:03 +0100] [6160] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:54:03 +0100] [6160] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:03 +0100] [6160] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:04 +0100] [6160] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:04 +0100] [6160] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:05 +0100] [6160] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:05 +0100] [6160] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:06 +0100] [6160] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:06 +0100] [6160] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:07 +0100] [6160] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:07 +0100] [6160] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:08 +0100] [6160] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:54:15 +0100] [6171] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:54:15 +0100] [6171] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:15 +0100] [6171] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:16 +0100] [6171] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:16 +0100] [6171] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:17 +0100] [6171] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:17 +0100] [6171] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:18 +0100] [6171] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:18 +0100] [6171] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:19 +0100] [6171] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:19 +0100] [6171] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:20 +0100] [6171] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:54:27 +0100] [6180] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:54:27 +0100] [6180] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:27 +0100] [6180] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:28 +0100] [6180] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:28 +0100] [6180] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:29 +0100] [6180] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:29 +0100] [6180] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:30 +0100] [6180] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:30 +0100] [6180] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:31 +0100] [6180] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:31 +0100] [6180] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:32 +0100] [6180] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:54:39 +0100] [6204] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:54:39 +0100] [6204] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:39 +0100] [6204] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:40 +0100] [6204] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:40 +0100] [6204] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:41 +0100] [6204] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:41 +0100] [6204] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:42 +0100] [6204] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:42 +0100] [6204] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:43 +0100] [6204] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:43 +0100] [6204] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:44 +0100] [6204] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:54:50 +0100] [6214] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:54:51 +0100] [6214] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:51 +0100] [6214] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:52 +0100] [6214] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:52 +0100] [6214] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:53 +0100] [6214] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:53 +0100] [6214] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:54 +0100] [6214] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:54 +0100] [6214] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:55 +0100] [6214] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:54:55 +0100] [6214] [ERROR] Retrying in 1 second.
[2016-03-06 22:54:56 +0100] [6214] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:55:02 +0100] [6225] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:55:02 +0100] [6225] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:02 +0100] [6225] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:03 +0100] [6225] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:03 +0100] [6225] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:04 +0100] [6225] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:04 +0100] [6225] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:05 +0100] [6225] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:05 +0100] [6225] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:06 +0100] [6225] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:06 +0100] [6225] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:07 +0100] [6225] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:55:14 +0100] [6235] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:55:14 +0100] [6235] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:14 +0100] [6235] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:15 +0100] [6235] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:15 +0100] [6235] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:16 +0100] [6235] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:16 +0100] [6235] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:17 +0100] [6235] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:17 +0100] [6235] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:18 +0100] [6235] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:18 +0100] [6235] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:19 +0100] [6235] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:55:26 +0100] [6246] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:55:26 +0100] [6246] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:26 +0100] [6246] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:27 +0100] [6246] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:27 +0100] [6246] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:28 +0100] [6246] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:28 +0100] [6246] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:29 +0100] [6246] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:29 +0100] [6246] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:30 +0100] [6246] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:30 +0100] [6246] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:31 +0100] [6246] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 10: --user=www-data : commande introuvable
[2016-03-06 22:55:38 +0100] [6260] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:55:38 +0100] [6260] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:38 +0100] [6260] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:39 +0100] [6260] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:39 +0100] [6260] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:40 +0100] [6260] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:40 +0100] [6260] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:41 +0100] [6260] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:41 +0100] [6260] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:42 +0100] [6260] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:55:42 +0100] [6260] [ERROR] Retrying in 1 second.
[2016-03-06 22:55:43 +0100] [6260] [ERROR] Can't connect to ('192.168.3.13', 8000)
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 9: caractère de fin de fichier (EOF) prématuré lors de la recherche du « " » correspondant
/home/pi/Prog/django/gesfi/start_gunicorn.sh: ligne 11: erreur de syntaxe : fin de fichier prématurée
[2016-03-06 22:56:06 +0100] [6280] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:56:06 +0100] [6280] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:06 +0100] [6280] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:07 +0100] [6280] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:07 +0100] [6280] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:08 +0100] [6280] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:08 +0100] [6280] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:09 +0100] [6280] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:09 +0100] [6280] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:10 +0100] [6280] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:10 +0100] [6280] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:11 +0100] [6280] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:56:19 +0100] [6303] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:56:19 +0100] [6303] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:19 +0100] [6303] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:20 +0100] [6303] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:20 +0100] [6303] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:21 +0100] [6303] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:21 +0100] [6303] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:23 +0100] [6303] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:23 +0100] [6303] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:24 +0100] [6303] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:24 +0100] [6303] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:25 +0100] [6303] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:56:31 +0100] [6322] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:56:31 +0100] [6322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:31 +0100] [6322] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:32 +0100] [6322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:32 +0100] [6322] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:33 +0100] [6322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:33 +0100] [6322] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:34 +0100] [6322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:34 +0100] [6322] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:35 +0100] [6322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:35 +0100] [6322] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:36 +0100] [6322] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:56:43 +0100] [6330] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:56:43 +0100] [6330] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:43 +0100] [6330] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:44 +0100] [6330] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:44 +0100] [6330] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:45 +0100] [6330] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:45 +0100] [6330] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:46 +0100] [6330] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:46 +0100] [6330] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:47 +0100] [6330] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:47 +0100] [6330] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:48 +0100] [6330] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:56:55 +0100] [6340] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:56:55 +0100] [6340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:55 +0100] [6340] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:56 +0100] [6340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:56 +0100] [6340] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:57 +0100] [6340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:57 +0100] [6340] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:58 +0100] [6340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:58 +0100] [6340] [ERROR] Retrying in 1 second.
[2016-03-06 22:56:59 +0100] [6340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:56:59 +0100] [6340] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:00 +0100] [6340] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:57:06 +0100] [6357] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:57:07 +0100] [6357] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:07 +0100] [6357] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:08 +0100] [6357] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:08 +0100] [6357] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:09 +0100] [6357] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:09 +0100] [6357] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:10 +0100] [6357] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:10 +0100] [6357] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:11 +0100] [6357] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:11 +0100] [6357] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:12 +0100] [6357] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:57:18 +0100] [6366] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:57:18 +0100] [6366] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:18 +0100] [6366] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:19 +0100] [6366] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:19 +0100] [6366] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:20 +0100] [6366] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:20 +0100] [6366] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:21 +0100] [6366] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:21 +0100] [6366] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:22 +0100] [6366] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:22 +0100] [6366] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:23 +0100] [6366] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:57:30 +0100] [6380] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:57:30 +0100] [6380] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:30 +0100] [6380] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:31 +0100] [6380] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:31 +0100] [6380] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:32 +0100] [6380] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:32 +0100] [6380] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:33 +0100] [6380] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:33 +0100] [6380] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:34 +0100] [6380] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:34 +0100] [6380] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:35 +0100] [6380] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:57:41 +0100] [6389] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:57:42 +0100] [6389] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:42 +0100] [6389] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:43 +0100] [6389] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:43 +0100] [6389] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:44 +0100] [6389] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:44 +0100] [6389] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:45 +0100] [6389] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:45 +0100] [6389] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:46 +0100] [6389] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:46 +0100] [6389] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:47 +0100] [6389] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:57:53 +0100] [6398] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:57:53 +0100] [6398] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:53 +0100] [6398] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:54 +0100] [6398] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:54 +0100] [6398] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:55 +0100] [6398] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:55 +0100] [6398] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:56 +0100] [6398] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:56 +0100] [6398] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:57 +0100] [6398] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:57:57 +0100] [6398] [ERROR] Retrying in 1 second.
[2016-03-06 22:57:58 +0100] [6398] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:58:05 +0100] [6406] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:58:05 +0100] [6406] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:05 +0100] [6406] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:06 +0100] [6406] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:06 +0100] [6406] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:07 +0100] [6406] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:07 +0100] [6406] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:08 +0100] [6406] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:08 +0100] [6406] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:09 +0100] [6406] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:09 +0100] [6406] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:10 +0100] [6406] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:58:16 +0100] [6419] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:58:16 +0100] [6419] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:16 +0100] [6419] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:17 +0100] [6419] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:17 +0100] [6419] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:18 +0100] [6419] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:18 +0100] [6419] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:19 +0100] [6419] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:19 +0100] [6419] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:20 +0100] [6419] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:20 +0100] [6419] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:21 +0100] [6419] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:58:28 +0100] [6427] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:58:28 +0100] [6427] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:28 +0100] [6427] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:29 +0100] [6427] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:29 +0100] [6427] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:30 +0100] [6427] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:30 +0100] [6427] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:31 +0100] [6427] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:31 +0100] [6427] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:32 +0100] [6427] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:32 +0100] [6427] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:33 +0100] [6427] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:58:40 +0100] [6439] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:58:40 +0100] [6439] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:40 +0100] [6439] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:41 +0100] [6439] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:41 +0100] [6439] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:42 +0100] [6439] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:42 +0100] [6439] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:43 +0100] [6439] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:43 +0100] [6439] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:44 +0100] [6439] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:44 +0100] [6439] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:45 +0100] [6439] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:58:51 +0100] [6447] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:58:51 +0100] [6447] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:51 +0100] [6447] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:52 +0100] [6447] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:52 +0100] [6447] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:53 +0100] [6447] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:53 +0100] [6447] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:54 +0100] [6447] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:54 +0100] [6447] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:55 +0100] [6447] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:58:55 +0100] [6447] [ERROR] Retrying in 1 second.
[2016-03-06 22:58:56 +0100] [6447] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:59:03 +0100] [6457] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:59:03 +0100] [6457] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:03 +0100] [6457] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:04 +0100] [6457] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:04 +0100] [6457] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:05 +0100] [6457] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:05 +0100] [6457] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:06 +0100] [6457] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:06 +0100] [6457] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:07 +0100] [6457] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:07 +0100] [6457] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:08 +0100] [6457] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:59:15 +0100] [6467] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:59:15 +0100] [6467] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:15 +0100] [6467] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:16 +0100] [6467] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:16 +0100] [6467] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:17 +0100] [6467] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:17 +0100] [6467] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:18 +0100] [6467] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:18 +0100] [6467] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:19 +0100] [6467] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:19 +0100] [6467] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:20 +0100] [6467] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:59:27 +0100] [6478] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:59:27 +0100] [6478] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:27 +0100] [6478] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:28 +0100] [6478] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:28 +0100] [6478] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:29 +0100] [6478] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:29 +0100] [6478] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:30 +0100] [6478] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:30 +0100] [6478] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:31 +0100] [6478] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:31 +0100] [6478] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:32 +0100] [6478] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:59:38 +0100] [6490] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:59:38 +0100] [6490] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:38 +0100] [6490] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:39 +0100] [6490] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:39 +0100] [6490] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:40 +0100] [6490] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:40 +0100] [6490] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:41 +0100] [6490] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:41 +0100] [6490] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:42 +0100] [6490] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:42 +0100] [6490] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:43 +0100] [6490] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 22:59:50 +0100] [6501] [INFO] Starting gunicorn 19.4.5
[2016-03-06 22:59:50 +0100] [6501] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:50 +0100] [6501] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:51 +0100] [6501] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:51 +0100] [6501] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:52 +0100] [6501] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:52 +0100] [6501] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:53 +0100] [6501] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:53 +0100] [6501] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:54 +0100] [6501] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 22:59:54 +0100] [6501] [ERROR] Retrying in 1 second.
[2016-03-06 22:59:55 +0100] [6501] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:00:02 +0100] [6512] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:00:02 +0100] [6512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:02 +0100] [6512] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:03 +0100] [6512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:03 +0100] [6512] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:04 +0100] [6512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:04 +0100] [6512] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:05 +0100] [6512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:05 +0100] [6512] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:06 +0100] [6512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:06 +0100] [6512] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:07 +0100] [6512] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:00:13 +0100] [6520] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:00:13 +0100] [6520] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:13 +0100] [6520] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:14 +0100] [6520] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:14 +0100] [6520] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:15 +0100] [6520] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:15 +0100] [6520] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:16 +0100] [6520] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:16 +0100] [6520] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:17 +0100] [6520] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:18 +0100] [6520] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:19 +0100] [6520] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:00:25 +0100] [6529] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:00:25 +0100] [6529] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:25 +0100] [6529] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:26 +0100] [6529] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:26 +0100] [6529] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:27 +0100] [6529] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:27 +0100] [6529] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:28 +0100] [6529] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:28 +0100] [6529] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:29 +0100] [6529] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:29 +0100] [6529] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:30 +0100] [6529] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:00:37 +0100] [6539] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:00:37 +0100] [6539] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:37 +0100] [6539] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:38 +0100] [6539] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:38 +0100] [6539] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:39 +0100] [6539] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:39 +0100] [6539] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:40 +0100] [6539] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:40 +0100] [6539] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:41 +0100] [6539] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:41 +0100] [6539] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:42 +0100] [6539] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:00:48 +0100] [6548] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:00:48 +0100] [6548] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:48 +0100] [6548] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:49 +0100] [6548] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:49 +0100] [6548] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:50 +0100] [6548] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:50 +0100] [6548] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:51 +0100] [6548] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:51 +0100] [6548] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:53 +0100] [6548] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:00:53 +0100] [6548] [ERROR] Retrying in 1 second.
[2016-03-06 23:00:54 +0100] [6548] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:01:00 +0100] [6560] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:01:00 +0100] [6560] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:00 +0100] [6560] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:01 +0100] [6560] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:01 +0100] [6560] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:02 +0100] [6560] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:02 +0100] [6560] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:03 +0100] [6560] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:03 +0100] [6560] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:04 +0100] [6560] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:04 +0100] [6560] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:05 +0100] [6560] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:01:12 +0100] [6570] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:01:12 +0100] [6570] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:12 +0100] [6570] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:13 +0100] [6570] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:13 +0100] [6570] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:14 +0100] [6570] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:14 +0100] [6570] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:15 +0100] [6570] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:15 +0100] [6570] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:16 +0100] [6570] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:16 +0100] [6570] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:17 +0100] [6570] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:01:23 +0100] [6580] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:01:23 +0100] [6580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:23 +0100] [6580] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:24 +0100] [6580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:24 +0100] [6580] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:25 +0100] [6580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:25 +0100] [6580] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:26 +0100] [6580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:26 +0100] [6580] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:27 +0100] [6580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:27 +0100] [6580] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:28 +0100] [6580] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:01:35 +0100] [6590] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:01:35 +0100] [6590] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:35 +0100] [6590] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:36 +0100] [6590] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:36 +0100] [6590] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:37 +0100] [6590] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:37 +0100] [6590] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:38 +0100] [6590] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:38 +0100] [6590] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:39 +0100] [6590] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:39 +0100] [6590] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:40 +0100] [6590] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:01:47 +0100] [6600] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:01:47 +0100] [6600] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:47 +0100] [6600] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:48 +0100] [6600] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:48 +0100] [6600] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:49 +0100] [6600] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:49 +0100] [6600] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:50 +0100] [6600] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:50 +0100] [6600] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:51 +0100] [6600] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:01:51 +0100] [6600] [ERROR] Retrying in 1 second.
[2016-03-06 23:01:52 +0100] [6600] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:02:04 +0100] [6610] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:02:04 +0100] [6610] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:04 +0100] [6610] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:05 +0100] [6610] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:05 +0100] [6610] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:06 +0100] [6610] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:06 +0100] [6610] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:07 +0100] [6610] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:07 +0100] [6610] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:08 +0100] [6610] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:08 +0100] [6610] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:09 +0100] [6610] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:02:21 +0100] [6622] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:02:22 +0100] [6622] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:22 +0100] [6622] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:23 +0100] [6622] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:23 +0100] [6622] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:24 +0100] [6622] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:24 +0100] [6622] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:25 +0100] [6622] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:25 +0100] [6622] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:26 +0100] [6622] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:26 +0100] [6622] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:27 +0100] [6622] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:02:39 +0100] [6634] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:02:39 +0100] [6634] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:39 +0100] [6634] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:40 +0100] [6634] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:40 +0100] [6634] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:41 +0100] [6634] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:41 +0100] [6634] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:42 +0100] [6634] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:42 +0100] [6634] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:43 +0100] [6634] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:43 +0100] [6634] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:44 +0100] [6634] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:02:57 +0100] [6644] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:02:57 +0100] [6644] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:57 +0100] [6644] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:58 +0100] [6644] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:58 +0100] [6644] [ERROR] Retrying in 1 second.
[2016-03-06 23:02:59 +0100] [6644] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:02:59 +0100] [6644] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:00 +0100] [6644] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:00 +0100] [6644] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:01 +0100] [6644] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:01 +0100] [6644] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:02 +0100] [6644] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:03:14 +0100] [6654] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:03:15 +0100] [6654] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:15 +0100] [6654] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:16 +0100] [6654] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:16 +0100] [6654] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:17 +0100] [6654] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:17 +0100] [6654] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:18 +0100] [6654] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:18 +0100] [6654] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:19 +0100] [6654] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:19 +0100] [6654] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:20 +0100] [6654] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:03:28 +0100] [6664] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:03:28 +0100] [6664] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:28 +0100] [6664] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:29 +0100] [6664] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:29 +0100] [6664] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:30 +0100] [6664] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:30 +0100] [6664] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:31 +0100] [6664] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:31 +0100] [6664] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:32 +0100] [6664] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:32 +0100] [6664] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:33 +0100] [6664] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:03:40 +0100] [6675] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:03:40 +0100] [6675] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:40 +0100] [6675] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:41 +0100] [6675] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:41 +0100] [6675] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:42 +0100] [6675] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:42 +0100] [6675] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:43 +0100] [6675] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:43 +0100] [6675] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:44 +0100] [6675] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:44 +0100] [6675] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:45 +0100] [6675] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:03:52 +0100] [6685] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:03:52 +0100] [6685] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:52 +0100] [6685] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:53 +0100] [6685] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:53 +0100] [6685] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:54 +0100] [6685] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:54 +0100] [6685] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:55 +0100] [6685] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:55 +0100] [6685] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:56 +0100] [6685] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:03:56 +0100] [6685] [ERROR] Retrying in 1 second.
[2016-03-06 23:03:57 +0100] [6685] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:04:04 +0100] [6695] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:04:04 +0100] [6695] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:04 +0100] [6695] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:05 +0100] [6695] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:05 +0100] [6695] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:06 +0100] [6695] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:06 +0100] [6695] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:07 +0100] [6695] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:07 +0100] [6695] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:08 +0100] [6695] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:08 +0100] [6695] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:09 +0100] [6695] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:04:15 +0100] [6705] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:04:15 +0100] [6705] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:15 +0100] [6705] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:16 +0100] [6705] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:16 +0100] [6705] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:17 +0100] [6705] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:17 +0100] [6705] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:18 +0100] [6705] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:18 +0100] [6705] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:19 +0100] [6705] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:19 +0100] [6705] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:20 +0100] [6705] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:04:27 +0100] [6717] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:04:27 +0100] [6717] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:27 +0100] [6717] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:28 +0100] [6717] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:28 +0100] [6717] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:29 +0100] [6717] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:29 +0100] [6717] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:30 +0100] [6717] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:30 +0100] [6717] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:31 +0100] [6717] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:31 +0100] [6717] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:32 +0100] [6717] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:04:38 +0100] [6729] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:04:39 +0100] [6729] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:39 +0100] [6729] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:40 +0100] [6729] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:40 +0100] [6729] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:41 +0100] [6729] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:41 +0100] [6729] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:42 +0100] [6729] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:42 +0100] [6729] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:43 +0100] [6729] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:43 +0100] [6729] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:44 +0100] [6729] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:04:50 +0100] [6738] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:04:51 +0100] [6738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:51 +0100] [6738] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:52 +0100] [6738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:52 +0100] [6738] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:53 +0100] [6738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:53 +0100] [6738] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:54 +0100] [6738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:54 +0100] [6738] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:55 +0100] [6738] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:04:55 +0100] [6738] [ERROR] Retrying in 1 second.
[2016-03-06 23:04:56 +0100] [6738] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:05:02 +0100] [6755] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:05:02 +0100] [6755] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:02 +0100] [6755] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:03 +0100] [6755] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:03 +0100] [6755] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:04 +0100] [6755] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:04 +0100] [6755] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:05 +0100] [6755] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:05 +0100] [6755] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:06 +0100] [6755] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:06 +0100] [6755] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:07 +0100] [6755] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:05:14 +0100] [6767] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:05:14 +0100] [6767] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:14 +0100] [6767] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:15 +0100] [6767] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:15 +0100] [6767] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:16 +0100] [6767] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:16 +0100] [6767] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:17 +0100] [6767] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:17 +0100] [6767] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:18 +0100] [6767] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:18 +0100] [6767] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:19 +0100] [6767] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:05:26 +0100] [6777] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:05:26 +0100] [6777] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:26 +0100] [6777] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:27 +0100] [6777] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:27 +0100] [6777] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:28 +0100] [6777] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:28 +0100] [6777] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:29 +0100] [6777] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:29 +0100] [6777] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:30 +0100] [6777] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:30 +0100] [6777] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:31 +0100] [6777] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:05:38 +0100] [6789] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:05:38 +0100] [6789] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:38 +0100] [6789] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:39 +0100] [6789] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:39 +0100] [6789] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:40 +0100] [6789] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:40 +0100] [6789] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:41 +0100] [6789] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:41 +0100] [6789] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:42 +0100] [6789] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:42 +0100] [6789] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:43 +0100] [6789] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:05:49 +0100] [6797] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:05:50 +0100] [6797] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:50 +0100] [6797] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:51 +0100] [6797] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:51 +0100] [6797] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:52 +0100] [6797] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:52 +0100] [6797] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:53 +0100] [6797] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:53 +0100] [6797] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:54 +0100] [6797] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:05:54 +0100] [6797] [ERROR] Retrying in 1 second.
[2016-03-06 23:05:55 +0100] [6797] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:06:01 +0100] [6807] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:06:01 +0100] [6807] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:01 +0100] [6807] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:02 +0100] [6807] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:02 +0100] [6807] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:03 +0100] [6807] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:03 +0100] [6807] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:04 +0100] [6807] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:04 +0100] [6807] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:05 +0100] [6807] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:05 +0100] [6807] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:06 +0100] [6807] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:06:13 +0100] [6817] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:06:13 +0100] [6817] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:13 +0100] [6817] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:14 +0100] [6817] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:14 +0100] [6817] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:15 +0100] [6817] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:15 +0100] [6817] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:16 +0100] [6817] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:16 +0100] [6817] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:17 +0100] [6817] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:17 +0100] [6817] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:18 +0100] [6817] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:06:24 +0100] [6827] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:06:25 +0100] [6827] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:25 +0100] [6827] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:26 +0100] [6827] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:26 +0100] [6827] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:27 +0100] [6827] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:27 +0100] [6827] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:28 +0100] [6827] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:28 +0100] [6827] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:29 +0100] [6827] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:29 +0100] [6827] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:30 +0100] [6827] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:06:41 +0100] [6838] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:06:42 +0100] [6838] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:42 +0100] [6838] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:43 +0100] [6838] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:43 +0100] [6838] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:44 +0100] [6838] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:44 +0100] [6838] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:45 +0100] [6838] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:45 +0100] [6838] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:46 +0100] [6838] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:46 +0100] [6838] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:47 +0100] [6838] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:06:56 +0100] [6853] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:06:56 +0100] [6853] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:56 +0100] [6853] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:57 +0100] [6853] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:57 +0100] [6853] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:58 +0100] [6853] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:58 +0100] [6853] [ERROR] Retrying in 1 second.
[2016-03-06 23:06:59 +0100] [6853] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:06:59 +0100] [6853] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:00 +0100] [6853] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:00 +0100] [6853] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:01 +0100] [6853] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:07:07 +0100] [6864] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:07:08 +0100] [6864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:08 +0100] [6864] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:09 +0100] [6864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:09 +0100] [6864] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:10 +0100] [6864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:10 +0100] [6864] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:11 +0100] [6864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:11 +0100] [6864] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:12 +0100] [6864] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:12 +0100] [6864] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:13 +0100] [6864] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:07:19 +0100] [6874] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:07:19 +0100] [6874] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:19 +0100] [6874] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:20 +0100] [6874] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:20 +0100] [6874] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:21 +0100] [6874] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:21 +0100] [6874] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:22 +0100] [6874] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:22 +0100] [6874] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:23 +0100] [6874] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:23 +0100] [6874] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:24 +0100] [6874] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:07:31 +0100] [6885] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:07:31 +0100] [6885] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:31 +0100] [6885] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:32 +0100] [6885] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:32 +0100] [6885] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:33 +0100] [6885] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:33 +0100] [6885] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:34 +0100] [6885] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:34 +0100] [6885] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:35 +0100] [6885] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:35 +0100] [6885] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:36 +0100] [6885] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:07:45 +0100] [6895] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:07:45 +0100] [6895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:45 +0100] [6895] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:46 +0100] [6895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:46 +0100] [6895] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:48 +0100] [6895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:48 +0100] [6895] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:49 +0100] [6895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:49 +0100] [6895] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:50 +0100] [6895] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:07:50 +0100] [6895] [ERROR] Retrying in 1 second.
[2016-03-06 23:07:51 +0100] [6895] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:08:01 +0100] [6910] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:08:01 +0100] [6910] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:01 +0100] [6910] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:02 +0100] [6910] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:02 +0100] [6910] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:03 +0100] [6910] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:03 +0100] [6910] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:04 +0100] [6910] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:04 +0100] [6910] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:05 +0100] [6910] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:05 +0100] [6910] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:06 +0100] [6910] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:08:15 +0100] [6926] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:08:15 +0100] [6926] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:15 +0100] [6926] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:16 +0100] [6926] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:16 +0100] [6926] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:17 +0100] [6926] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:17 +0100] [6926] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:18 +0100] [6926] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:18 +0100] [6926] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:19 +0100] [6926] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:19 +0100] [6926] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:20 +0100] [6926] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:08:27 +0100] [6939] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:08:27 +0100] [6939] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:27 +0100] [6939] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:28 +0100] [6939] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:28 +0100] [6939] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:29 +0100] [6939] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:29 +0100] [6939] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:30 +0100] [6939] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:30 +0100] [6939] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:31 +0100] [6939] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:31 +0100] [6939] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:32 +0100] [6939] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:08:39 +0100] [6949] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:08:39 +0100] [6949] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:39 +0100] [6949] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:40 +0100] [6949] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:40 +0100] [6949] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:41 +0100] [6949] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:41 +0100] [6949] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:42 +0100] [6949] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:42 +0100] [6949] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:43 +0100] [6949] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:43 +0100] [6949] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:44 +0100] [6949] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:08:51 +0100] [6961] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:08:51 +0100] [6961] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:51 +0100] [6961] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:52 +0100] [6961] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:52 +0100] [6961] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:53 +0100] [6961] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:53 +0100] [6961] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:54 +0100] [6961] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:54 +0100] [6961] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:55 +0100] [6961] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:08:55 +0100] [6961] [ERROR] Retrying in 1 second.
[2016-03-06 23:08:56 +0100] [6961] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:09:03 +0100] [6980] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:09:03 +0100] [6980] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:03 +0100] [6980] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:04 +0100] [6980] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:04 +0100] [6980] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:05 +0100] [6980] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:05 +0100] [6980] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:06 +0100] [6980] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:06 +0100] [6980] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:07 +0100] [6980] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:07 +0100] [6980] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:08 +0100] [6980] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:09:14 +0100] [6991] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:09:15 +0100] [6991] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:15 +0100] [6991] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:16 +0100] [6991] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:16 +0100] [6991] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:17 +0100] [6991] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:17 +0100] [6991] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:18 +0100] [6991] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:18 +0100] [6991] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:19 +0100] [6991] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:19 +0100] [6991] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:20 +0100] [6991] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:09:26 +0100] [7002] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:09:26 +0100] [7002] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:26 +0100] [7002] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:27 +0100] [7002] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:27 +0100] [7002] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:28 +0100] [7002] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:28 +0100] [7002] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:29 +0100] [7002] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:29 +0100] [7002] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:30 +0100] [7002] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:30 +0100] [7002] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:31 +0100] [7002] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:09:38 +0100] [7014] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:09:38 +0100] [7014] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:38 +0100] [7014] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:39 +0100] [7014] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:39 +0100] [7014] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:40 +0100] [7014] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:40 +0100] [7014] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:41 +0100] [7014] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:41 +0100] [7014] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:42 +0100] [7014] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:42 +0100] [7014] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:43 +0100] [7014] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:09:50 +0100] [7028] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:09:50 +0100] [7028] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:50 +0100] [7028] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:51 +0100] [7028] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:51 +0100] [7028] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:52 +0100] [7028] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:52 +0100] [7028] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:53 +0100] [7028] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:53 +0100] [7028] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:54 +0100] [7028] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:09:54 +0100] [7028] [ERROR] Retrying in 1 second.
[2016-03-06 23:09:55 +0100] [7028] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:10:01 +0100] [7038] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:10:01 +0100] [7038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:01 +0100] [7038] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:02 +0100] [7038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:02 +0100] [7038] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:03 +0100] [7038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:03 +0100] [7038] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:04 +0100] [7038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:04 +0100] [7038] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:05 +0100] [7038] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:05 +0100] [7038] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:06 +0100] [7038] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:10:13 +0100] [7050] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:10:13 +0100] [7050] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:13 +0100] [7050] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:14 +0100] [7050] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:14 +0100] [7050] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:15 +0100] [7050] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:15 +0100] [7050] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:16 +0100] [7050] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:16 +0100] [7050] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:17 +0100] [7050] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:17 +0100] [7050] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:18 +0100] [7050] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:10:25 +0100] [7059] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:10:25 +0100] [7059] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:25 +0100] [7059] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:26 +0100] [7059] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:26 +0100] [7059] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:27 +0100] [7059] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:27 +0100] [7059] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:28 +0100] [7059] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:28 +0100] [7059] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:29 +0100] [7059] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:29 +0100] [7059] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:30 +0100] [7059] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:10:39 +0100] [7071] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:10:40 +0100] [7071] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:40 +0100] [7071] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:41 +0100] [7071] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:41 +0100] [7071] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:42 +0100] [7071] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:42 +0100] [7071] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:43 +0100] [7071] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:43 +0100] [7071] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:44 +0100] [7071] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:44 +0100] [7071] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:45 +0100] [7071] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:10:58 +0100] [7109] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:10:58 +0100] [7109] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:58 +0100] [7109] [ERROR] Retrying in 1 second.
[2016-03-06 23:10:59 +0100] [7109] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:10:59 +0100] [7109] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:00 +0100] [7109] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:00 +0100] [7109] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:01 +0100] [7109] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:01 +0100] [7109] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:02 +0100] [7109] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:02 +0100] [7109] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:03 +0100] [7109] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:11:15 +0100] [7120] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:11:15 +0100] [7120] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:15 +0100] [7120] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:16 +0100] [7120] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:16 +0100] [7120] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:17 +0100] [7120] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:17 +0100] [7120] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:18 +0100] [7120] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:18 +0100] [7120] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:19 +0100] [7120] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:19 +0100] [7120] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:20 +0100] [7120] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:11:34 +0100] [7134] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:11:34 +0100] [7134] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:34 +0100] [7134] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:35 +0100] [7134] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:35 +0100] [7134] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:36 +0100] [7134] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:36 +0100] [7134] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:37 +0100] [7134] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:37 +0100] [7134] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:38 +0100] [7134] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:38 +0100] [7134] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:39 +0100] [7134] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:11:53 +0100] [7146] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:11:53 +0100] [7146] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:53 +0100] [7146] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:54 +0100] [7146] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:54 +0100] [7146] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:55 +0100] [7146] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:55 +0100] [7146] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:56 +0100] [7146] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:56 +0100] [7146] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:57 +0100] [7146] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:11:57 +0100] [7146] [ERROR] Retrying in 1 second.
[2016-03-06 23:11:58 +0100] [7146] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:12:13 +0100] [7157] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:12:13 +0100] [7157] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:13 +0100] [7157] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:14 +0100] [7157] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:14 +0100] [7157] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:15 +0100] [7157] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:15 +0100] [7157] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:16 +0100] [7157] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:16 +0100] [7157] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:17 +0100] [7157] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:17 +0100] [7157] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:18 +0100] [7157] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:12:32 +0100] [7168] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:12:33 +0100] [7168] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:33 +0100] [7168] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:34 +0100] [7168] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:34 +0100] [7168] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:35 +0100] [7168] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:35 +0100] [7168] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:36 +0100] [7168] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:36 +0100] [7168] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:37 +0100] [7168] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:37 +0100] [7168] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:38 +0100] [7168] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:12:51 +0100] [7179] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:12:51 +0100] [7179] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:51 +0100] [7179] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:53 +0100] [7179] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:53 +0100] [7179] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:54 +0100] [7179] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:54 +0100] [7179] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:55 +0100] [7179] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:55 +0100] [7179] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:56 +0100] [7179] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:12:56 +0100] [7179] [ERROR] Retrying in 1 second.
[2016-03-06 23:12:57 +0100] [7179] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:13:10 +0100] [7191] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:13:11 +0100] [7191] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:11 +0100] [7191] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:12 +0100] [7191] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:12 +0100] [7191] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:13 +0100] [7191] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:13 +0100] [7191] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:14 +0100] [7191] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:14 +0100] [7191] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:15 +0100] [7191] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:15 +0100] [7191] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:16 +0100] [7191] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:13:24 +0100] [7205] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:13:24 +0100] [7205] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:24 +0100] [7205] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:25 +0100] [7205] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:25 +0100] [7205] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:26 +0100] [7205] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:26 +0100] [7205] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:27 +0100] [7205] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:27 +0100] [7205] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:28 +0100] [7205] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:28 +0100] [7205] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:29 +0100] [7205] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:13:36 +0100] [7230] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:13:36 +0100] [7230] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:36 +0100] [7230] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:37 +0100] [7230] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:37 +0100] [7230] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:38 +0100] [7230] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:38 +0100] [7230] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:39 +0100] [7230] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:39 +0100] [7230] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:40 +0100] [7230] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:40 +0100] [7230] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:41 +0100] [7230] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:13:47 +0100] [7244] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:13:48 +0100] [7244] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:48 +0100] [7244] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:49 +0100] [7244] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:49 +0100] [7244] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:50 +0100] [7244] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:50 +0100] [7244] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:51 +0100] [7244] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:51 +0100] [7244] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:52 +0100] [7244] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:52 +0100] [7244] [ERROR] Retrying in 1 second.
[2016-03-06 23:13:53 +0100] [7244] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:13:59 +0100] [7253] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:13:59 +0100] [7253] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:13:59 +0100] [7253] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:00 +0100] [7253] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:00 +0100] [7253] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:01 +0100] [7253] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:01 +0100] [7253] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:02 +0100] [7253] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:02 +0100] [7253] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:03 +0100] [7253] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:03 +0100] [7253] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:04 +0100] [7253] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:14:11 +0100] [7264] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:14:11 +0100] [7264] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:11 +0100] [7264] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:12 +0100] [7264] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:12 +0100] [7264] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:13 +0100] [7264] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:13 +0100] [7264] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:14 +0100] [7264] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:14 +0100] [7264] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:15 +0100] [7264] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:15 +0100] [7264] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:16 +0100] [7264] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:14:23 +0100] [7272] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:14:23 +0100] [7272] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:23 +0100] [7272] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:24 +0100] [7272] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:24 +0100] [7272] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:25 +0100] [7272] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:25 +0100] [7272] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:26 +0100] [7272] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:26 +0100] [7272] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:27 +0100] [7272] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:27 +0100] [7272] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:28 +0100] [7272] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:14:34 +0100] [7285] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:14:34 +0100] [7285] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:34 +0100] [7285] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:36 +0100] [7285] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:36 +0100] [7285] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:37 +0100] [7285] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:37 +0100] [7285] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:38 +0100] [7285] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:38 +0100] [7285] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:39 +0100] [7285] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:39 +0100] [7285] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:40 +0100] [7285] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:14:46 +0100] [7294] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:14:46 +0100] [7294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:46 +0100] [7294] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:47 +0100] [7294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:47 +0100] [7294] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:48 +0100] [7294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:48 +0100] [7294] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:49 +0100] [7294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:49 +0100] [7294] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:50 +0100] [7294] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:50 +0100] [7294] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:51 +0100] [7294] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:14:58 +0100] [7305] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:14:58 +0100] [7305] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:58 +0100] [7305] [ERROR] Retrying in 1 second.
[2016-03-06 23:14:59 +0100] [7305] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:14:59 +0100] [7305] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:00 +0100] [7305] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:00 +0100] [7305] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:01 +0100] [7305] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:01 +0100] [7305] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:02 +0100] [7305] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:02 +0100] [7305] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:03 +0100] [7305] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:15:09 +0100] [7314] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:15:09 +0100] [7314] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:09 +0100] [7314] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:10 +0100] [7314] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:10 +0100] [7314] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:11 +0100] [7314] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:11 +0100] [7314] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:12 +0100] [7314] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:12 +0100] [7314] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:13 +0100] [7314] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:13 +0100] [7314] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:14 +0100] [7314] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:15:21 +0100] [7322] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:15:21 +0100] [7322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:21 +0100] [7322] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:22 +0100] [7322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:22 +0100] [7322] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:23 +0100] [7322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:23 +0100] [7322] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:24 +0100] [7322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:24 +0100] [7322] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:25 +0100] [7322] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:25 +0100] [7322] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:26 +0100] [7322] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:15:37 +0100] [7340] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:15:37 +0100] [7340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:37 +0100] [7340] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:38 +0100] [7340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:38 +0100] [7340] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:39 +0100] [7340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:39 +0100] [7340] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:40 +0100] [7340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:40 +0100] [7340] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:41 +0100] [7340] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:41 +0100] [7340] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:42 +0100] [7340] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:15:52 +0100] [7356] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:15:53 +0100] [7356] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:53 +0100] [7356] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:54 +0100] [7356] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:54 +0100] [7356] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:55 +0100] [7356] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:55 +0100] [7356] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:56 +0100] [7356] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:56 +0100] [7356] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:57 +0100] [7356] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:15:57 +0100] [7356] [ERROR] Retrying in 1 second.
[2016-03-06 23:15:58 +0100] [7356] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:16:06 +0100] [7368] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:16:06 +0100] [7368] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:06 +0100] [7368] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:07 +0100] [7368] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:07 +0100] [7368] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:08 +0100] [7368] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:08 +0100] [7368] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:09 +0100] [7368] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:09 +0100] [7368] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:10 +0100] [7368] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:10 +0100] [7368] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:11 +0100] [7368] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:16:19 +0100] [7385] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:16:19 +0100] [7385] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:19 +0100] [7385] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:20 +0100] [7385] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:20 +0100] [7385] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:21 +0100] [7385] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:21 +0100] [7385] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:22 +0100] [7385] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:22 +0100] [7385] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:23 +0100] [7385] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:23 +0100] [7385] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:24 +0100] [7385] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:16:30 +0100] [7410] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:16:30 +0100] [7410] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:30 +0100] [7410] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:31 +0100] [7410] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:31 +0100] [7410] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:32 +0100] [7410] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:32 +0100] [7410] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:33 +0100] [7410] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:33 +0100] [7410] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:34 +0100] [7410] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:34 +0100] [7410] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:35 +0100] [7410] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:16:42 +0100] [7420] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:16:42 +0100] [7420] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:42 +0100] [7420] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:43 +0100] [7420] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:43 +0100] [7420] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:44 +0100] [7420] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:44 +0100] [7420] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:45 +0100] [7420] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:45 +0100] [7420] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:46 +0100] [7420] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:46 +0100] [7420] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:47 +0100] [7420] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:16:53 +0100] [7430] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:16:54 +0100] [7430] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:54 +0100] [7430] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:55 +0100] [7430] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:55 +0100] [7430] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:56 +0100] [7430] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:56 +0100] [7430] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:57 +0100] [7430] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:57 +0100] [7430] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:58 +0100] [7430] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:16:58 +0100] [7430] [ERROR] Retrying in 1 second.
[2016-03-06 23:16:59 +0100] [7430] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:17:05 +0100] [7438] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:17:06 +0100] [7438] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:06 +0100] [7438] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:07 +0100] [7438] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:07 +0100] [7438] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:08 +0100] [7438] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:08 +0100] [7438] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:09 +0100] [7438] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:09 +0100] [7438] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:10 +0100] [7438] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:10 +0100] [7438] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:11 +0100] [7438] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:17:17 +0100] [7471] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:17:17 +0100] [7471] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:17 +0100] [7471] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:18 +0100] [7471] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:18 +0100] [7471] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:19 +0100] [7471] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:19 +0100] [7471] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:20 +0100] [7471] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:20 +0100] [7471] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:21 +0100] [7471] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:21 +0100] [7471] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:22 +0100] [7471] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:17:29 +0100] [7479] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:17:29 +0100] [7479] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:29 +0100] [7479] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:30 +0100] [7479] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:30 +0100] [7479] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:31 +0100] [7479] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:31 +0100] [7479] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:32 +0100] [7479] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:32 +0100] [7479] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:33 +0100] [7479] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:33 +0100] [7479] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:34 +0100] [7479] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:17:40 +0100] [7492] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:17:40 +0100] [7492] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:40 +0100] [7492] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:41 +0100] [7492] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:41 +0100] [7492] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:42 +0100] [7492] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:42 +0100] [7492] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:43 +0100] [7492] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:43 +0100] [7492] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:45 +0100] [7492] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:45 +0100] [7492] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:46 +0100] [7492] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:17:54 +0100] [7502] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:17:54 +0100] [7502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:54 +0100] [7502] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:55 +0100] [7502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:55 +0100] [7502] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:56 +0100] [7502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:56 +0100] [7502] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:57 +0100] [7502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:57 +0100] [7502] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:58 +0100] [7502] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:17:58 +0100] [7502] [ERROR] Retrying in 1 second.
[2016-03-06 23:17:59 +0100] [7502] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:18:05 +0100] [7512] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:18:06 +0100] [7512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:06 +0100] [7512] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:07 +0100] [7512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:07 +0100] [7512] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:08 +0100] [7512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:08 +0100] [7512] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:09 +0100] [7512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:09 +0100] [7512] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:10 +0100] [7512] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:10 +0100] [7512] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:11 +0100] [7512] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:18:17 +0100] [7523] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:18:17 +0100] [7523] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:18 +0100] [7523] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:19 +0100] [7523] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:19 +0100] [7523] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:20 +0100] [7523] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:20 +0100] [7523] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:21 +0100] [7523] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:21 +0100] [7523] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:22 +0100] [7523] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:22 +0100] [7523] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:23 +0100] [7523] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:18:30 +0100] [7566] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:18:30 +0100] [7566] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:30 +0100] [7566] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:31 +0100] [7566] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:31 +0100] [7566] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:32 +0100] [7566] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:32 +0100] [7566] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:33 +0100] [7566] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:33 +0100] [7566] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:34 +0100] [7566] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:34 +0100] [7566] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:35 +0100] [7566] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:18:47 +0100] [7580] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:18:47 +0100] [7580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:47 +0100] [7580] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:48 +0100] [7580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:48 +0100] [7580] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:49 +0100] [7580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:49 +0100] [7580] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:50 +0100] [7580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:50 +0100] [7580] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:51 +0100] [7580] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:18:51 +0100] [7580] [ERROR] Retrying in 1 second.
[2016-03-06 23:18:52 +0100] [7580] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:19:01 +0100] [7594] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:19:01 +0100] [7594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:01 +0100] [7594] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:02 +0100] [7594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:02 +0100] [7594] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:03 +0100] [7594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:03 +0100] [7594] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:04 +0100] [7594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:04 +0100] [7594] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:05 +0100] [7594] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:05 +0100] [7594] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:06 +0100] [7594] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:19:14 +0100] [7609] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:19:14 +0100] [7609] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:15 +0100] [7609] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:16 +0100] [7609] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:16 +0100] [7609] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:17 +0100] [7609] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:17 +0100] [7609] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:18 +0100] [7609] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:18 +0100] [7609] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:19 +0100] [7609] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:19 +0100] [7609] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:20 +0100] [7609] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-06 23:19:26 +0100] [7620] [INFO] Starting gunicorn 19.4.5
[2016-03-06 23:19:26 +0100] [7620] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:26 +0100] [7620] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:27 +0100] [7620] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:27 +0100] [7620] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:28 +0100] [7620] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:28 +0100] [7620] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:29 +0100] [7620] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:29 +0100] [7620] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:30 +0100] [7620] [ERROR] Connection in use: ('192.168.3.13', 8000)
[2016-03-06 23:19:30 +0100] [7620] [ERROR] Retrying in 1 second.
[2016-03-06 23:19:31 +0100] [7620] [ERROR] Can't connect to ('192.168.3.13', 8000)
[2016-03-11 22:06:43 +0100] [746] [INFO] Starting gunicorn 19.4.5
[2016-03-11 22:06:43 +0100] [746] [INFO] Listening at: http://192.168.3.13:8000 (746)
[2016-03-11 22:06:43 +0100] [746] [INFO] Using worker: sync
[2016-03-11 22:06:43 +0100] [808] [INFO] Booting worker with pid: 808
[2016-03-11 22:06:44 +0100] [809] [INFO] Booting worker with pid: 809
[2016-03-11 22:07:14 +0100] [746] [CRITICAL] WORKER TIMEOUT (pid:808)
[2016-03-11 22:07:14 +0100] [746] [CRITICAL] WORKER TIMEOUT (pid:809)
[2016-03-11 21:07:14 +0000] [808] [INFO] Worker exiting (pid: 808)
[2016-03-11 21:07:14 +0000] [809] [INFO] Worker exiting (pid: 809)
[2016-03-11 22:07:15 +0100] [869] [INFO] Booting worker with pid: 869
[2016-03-11 22:07:15 +0100] [870] [INFO] Booting worker with pid: 870
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
[2016-03-14 18:38:00 +0100] [757] [INFO] Starting gunicorn 19.4.5
[2016-03-14 18:38:00 +0100] [757] [INFO] Listening at: http://192.168.3.13:8000 (757)
[2016-03-14 18:38:00 +0100] [757] [INFO] Using worker: sync
[2016-03-14 18:38:00 +0100] [811] [INFO] Booting worker with pid: 811
[2016-03-14 18:38:00 +0100] [812] [INFO] Booting worker with pid: 812
[2016-03-14 18:38:30 +0100] [757] [CRITICAL] WORKER TIMEOUT (pid:811)
[2016-03-14 18:38:30 +0100] [757] [CRITICAL] WORKER TIMEOUT (pid:812)
[2016-03-14 17:38:30 +0000] [811] [INFO] Worker exiting (pid: 811)
[2016-03-14 17:38:30 +0000] [812] [INFO] Worker exiting (pid: 812)
[2016-03-14 18:38:31 +0100] [863] [INFO] Booting worker with pid: 863
[2016-03-14 18:38:32 +0100] [864] [INFO] Booting worker with pid: 864
[2016-03-18 08:18:12 +0100] [800] [INFO] Starting gunicorn 19.4.5
[2016-03-18 08:18:12 +0100] [800] [INFO] Listening at: http://192.168.3.13:8000 (800)
[2016-03-18 08:18:12 +0100] [800] [INFO] Using worker: sync
[2016-03-18 08:18:12 +0100] [853] [INFO] Booting worker with pid: 853
[2016-03-18 08:18:12 +0100] [855] [INFO] Booting worker with pid: 855
